### ISSUE TITLE
有关COLA-MADDPG的实现问题

### ISSUE THREAD

**Issue by wjh-scut** [deligentfool/COLA#1]
同学你好，我想请问一下，你在文章《Consensus Learning for Cooperative Multi-Agent Reinforcement Learning》中提到使用COLA-MADDPG在MPE环境下进行了实验，请问这部分的代码在哪里可以找到啊？

**Comment by deligentfool** [comment]
你好，相关代码可以在https://github.com/deligentfool/COLA_MADDPG 中找到

**Comment by wjh-scut** [comment]
谢谢！
